#include <map>
#include <vector>

enum MBVQ { CMYW, MYGC, RGMY, KRGB, RGBM, CMGB };

enum COLOR { RED, GREEN, BLUE, WHITE, MAGENTA, CYAN, YELLOW, BLACK };

enum DIFFUSION_KERNEL { FLOYD_STEINBERG, JARVIS_JUDICE_NINKE, STUCKI };