#ifndef DIFFUSION_KERNEL_H
#define DIFFUSION_KERNEL_H

enum MBVQ { CMYW, MYGC, RGMY, KRGB, RGBM, CMGB };

enum COLOR { RED, GREEN, BLUE, WHITE, MAGENTA, CYAN, YELLOW, BLACK };

enum DIFFUSION_KERNEL {
  FLOYD_STEINBERG = 1,
  JARVIS_JUDICE_NINKE = 2,
  STUCKI = 3
};

#endif